version: "3.7"

services:
  ghost:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.josepostiga-blog.entrypoints=https"
      - "traefik.http.routers.josepostiga-blog.tls=true"
      - "traefik.http.routers.josepostiga-blog.tls.certResolver=letsencrypt"
      - "traefik.http.routers.josepostiga-blog.rule=Host(`josepostiga.com`)"
    environment:
      url: https://josepostiga.com
