version: "3.7"

services:
  ghost:
    image: ghost:3-alpine
    restart: always
    expose:
      - 2368
    environment:
      database__client: sqlite3
    volumes:
      - ghost-fs:/var/lib/ghost/content
    networks:
      - web

volumes:
  ghost-fs:

networks:
  web:
    external: true
